"""initial_unified_schema

Revision ID: a52899423b9f
Revises: 
Create Date: 2026-07-10 12:54:37.681991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a52899423b9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('time_display', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarms_id'), 'alarms', ['id'], unique=False)
    op.create_index(op.f('ix_alarms_severity'), 'alarms', ['severity'], unique=False)
    op.create_index(op.f('ix_alarms_source'), 'alarms', ['source'], unique=False)
    op.create_index(op.f('ix_alarms_status'), 'alarms', ['status'], unique=False)
    op.create_index(op.f('ix_alarms_timestamp'), 'alarms', ['timestamp'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('approvals', sa.String(), nullable=True),
    sa.Column('rollback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_name'), 'audit_logs', ['user_name'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('persona', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_index(op.f('ix_chat_history_persona'), 'chat_history', ['persona'], unique=False)
    op.create_index(op.f('ix_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_history_timestamp'), 'chat_history', ['timestamp'], unique=False)
    op.create_table('devices',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_devices_name'), 'devices', ['name'], unique=False)
    op.create_table('discovery_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('subnet', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('devices_found', sa.Integer(), nullable=False),
    sa.Column('log_output', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_logs_id'), 'discovery_logs', ['id'], unique=False)
    op.create_index(op.f('ix_discovery_logs_status'), 'discovery_logs', ['status'], unique=False)
    op.create_index(op.f('ix_discovery_logs_subnet'), 'discovery_logs', ['subnet'], unique=False)
    op.create_index(op.f('ix_discovery_logs_timestamp'), 'discovery_logs', ['timestamp'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_severity'), 'events', ['severity'], unique=False)
    op.create_index(op.f('ix_events_source'), 'events', ['source'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('business_impact', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('root_cause', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('evidence', sa.String(), nullable=True),
    sa.Column('remediation_commands', sa.String(), nullable=True),
    sa.Column('verification_steps', sa.String(), nullable=True),
    sa.Column('rollback_plan', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('repair_time', sa.String(), nullable=True),
    sa.Column('engineering_report', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_device_name'), 'incidents', ['device_name'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_timestamp'), 'incidents', ['timestamp'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default='0'),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    op.create_table('vault_secrets',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('secret_type', sa.String(), nullable=False),
    sa.Column('encrypted_value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_rotated', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_vault_secrets_name'), 'vault_secrets', ['name'], unique=False)
    op.create_index(op.f('ix_vault_secrets_secret_type'), 'vault_secrets', ['secret_type'], unique=False)
    op.create_table('configuration_backups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('running_config', sa.Text(), nullable=False),
    sa.Column('startup_config', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['device_name'], ['devices.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_backups_device_name'), 'configuration_backups', ['device_name'], unique=False)
    op.create_index(op.f('ix_configuration_backups_id'), 'configuration_backups', ['id'], unique=False)
    op.create_index(op.f('ix_configuration_backups_timestamp'), 'configuration_backups', ['timestamp'], unique=False)
    op.create_table('interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('speed', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['device_name'], ['devices.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interfaces_device_name'), 'interfaces', ['device_name'], unique=False)
    op.create_index(op.f('ix_interfaces_id'), 'interfaces', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('telemetry_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=False),
    sa.Column('ping_rtt', sa.Float(), nullable=True),
    sa.Column('min_rtt', sa.Float(), nullable=True),
    sa.Column('max_rtt', sa.Float(), nullable=True),
    sa.Column('packet_loss', sa.Float(), nullable=True),
    sa.Column('jitter', sa.Float(), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('ram', sa.Integer(), nullable=True),
    sa.Column('interface_errors', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('disk_utilization', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_name'], ['devices.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_logs_device_name'), 'telemetry_logs', ['device_name'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_id'), 'telemetry_logs', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_timestamp'), 'telemetry_logs', ['timestamp'], unique=False)
    op.create_table('ai_analysis_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('scenario', sa.String(length=100), nullable=True),
    sa.Column('safety_status', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_history_id'), 'ai_analysis_history', ['id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_history_scenario'), 'ai_analysis_history', ['scenario'], unique=False)
    op.create_index(op.f('ix_ai_analysis_history_timestamp'), 'ai_analysis_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ai_analysis_history_user_id'), 'ai_analysis_history', ['user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_timestamp'), 'notifications', ['timestamp'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=128), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_refresh_tokens_id'), 'user_refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_user_refresh_tokens_is_revoked'), 'user_refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_user_refresh_tokens_token'), 'user_refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_user_refresh_tokens_user_id'), 'user_refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_refresh_tokens_user_id'), table_name='user_refresh_tokens')
    op.drop_index(op.f('ix_user_refresh_tokens_token'), table_name='user_refresh_tokens')
    op.drop_index(op.f('ix_user_refresh_tokens_is_revoked'), table_name='user_refresh_tokens')
    op.drop_index(op.f('ix_user_refresh_tokens_id'), table_name='user_refresh_tokens')
    op.drop_table('user_refresh_tokens')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_timestamp'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ai_analysis_history_user_id'), table_name='ai_analysis_history')
    op.drop_index(op.f('ix_ai_analysis_history_timestamp'), table_name='ai_analysis_history')
    op.drop_index(op.f('ix_ai_analysis_history_scenario'), table_name='ai_analysis_history')
    op.drop_index(op.f('ix_ai_analysis_history_id'), table_name='ai_analysis_history')
    op.drop_table('ai_analysis_history')
    op.drop_index(op.f('ix_telemetry_logs_timestamp'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_id'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_device_name'), table_name='telemetry_logs')
    op.drop_table('telemetry_logs')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_interfaces_id'), table_name='interfaces')
    op.drop_index(op.f('ix_interfaces_device_name'), table_name='interfaces')
    op.drop_table('interfaces')
    op.drop_index(op.f('ix_configuration_backups_timestamp'), table_name='configuration_backups')
    op.drop_index(op.f('ix_configuration_backups_id'), table_name='configuration_backups')
    op.drop_index(op.f('ix_configuration_backups_device_name'), table_name='configuration_backups')
    op.drop_table('configuration_backups')
    op.drop_index(op.f('ix_vault_secrets_secret_type'), table_name='vault_secrets')
    op.drop_index(op.f('ix_vault_secrets_name'), table_name='vault_secrets')
    op.drop_table('vault_secrets')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_incidents_timestamp'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_device_name'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_source'), table_name='events')
    op.drop_index(op.f('ix_events_severity'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_discovery_logs_timestamp'), table_name='discovery_logs')
    op.drop_index(op.f('ix_discovery_logs_subnet'), table_name='discovery_logs')
    op.drop_index(op.f('ix_discovery_logs_status'), table_name='discovery_logs')
    op.drop_index(op.f('ix_discovery_logs_id'), table_name='discovery_logs')
    op.drop_table('discovery_logs')
    op.drop_index(op.f('ix_devices_name'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_chat_history_timestamp'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_persona'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_audit_logs_user_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alarms_timestamp'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_status'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_source'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_severity'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_id'), table_name='alarms')
    op.drop_table('alarms')
    # ### end Alembic commands ###
