"""phase1_hardening_additions

Revision ID: c8a1493c58b1
Revises: a52899423b9f
Create Date: 2026-07-11 13:10:17.037894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a1493c58b1'
down_revision: Union[str, Sequence[str], None] = 'a52899423b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('output_log', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_jobs_device_name'), 'automation_jobs', ['device_name'], unique=False)
    op.create_index(op.f('ix_automation_jobs_id'), 'automation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_automation_jobs_job_id'), 'automation_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_automation_jobs_status'), 'automation_jobs', ['status'], unique=False)
    op.create_table('background_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_tasks_id'), 'background_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_background_tasks_status'), 'background_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_background_tasks_task_id'), 'background_tasks', ['task_id'], unique=True)
    op.create_table('slack_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('persona', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_messages_channel_id'), 'slack_messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_slack_messages_id'), 'slack_messages', ['id'], unique=False)
    op.create_index(op.f('ix_slack_messages_timestamp'), 'slack_messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_slack_messages_user_id'), 'slack_messages', ['user_id'], unique=False)
    op.create_table('compliance_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.String(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_reports_generated_at'), 'compliance_reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_compliance_reports_id'), 'compliance_reports', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_reports_incident_id'), 'compliance_reports', ['incident_id'], unique=False)
    op.create_table('incident_timelines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('status_from', sa.String(length=50), nullable=False),
    sa.Column('status_to', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_timelines_changed_at'), 'incident_timelines', ['changed_at'], unique=False)
    op.create_index(op.f('ix_incident_timelines_id'), 'incident_timelines', ['id'], unique=False)
    op.create_index(op.f('ix_incident_timelines_incident_id'), 'incident_timelines', ['incident_id'], unique=False)
    op.add_column('incidents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('incidents', sa.Column('assigned_to', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('resolved_by', sa.String(), nullable=True))
    op.add_column('telemetry_logs', sa.Column('bw_in', sa.Float(), nullable=True))
    op.add_column('telemetry_logs', sa.Column('bw_out', sa.Float(), nullable=True))
    op.add_column('telemetry_logs', sa.Column('vpn_tunnels_up', sa.Integer(), nullable=True))
    op.add_column('telemetry_logs', sa.Column('bgp_peer_status', sa.String(length=50), nullable=True))
    op.add_column('telemetry_logs', sa.Column('ospf_neighbor_count', sa.Integer(), nullable=True))
    op.add_column('telemetry_logs', sa.Column('fw_sessions', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'email')
    op.drop_column('telemetry_logs', 'fw_sessions')
    op.drop_column('telemetry_logs', 'ospf_neighbor_count')
    op.drop_column('telemetry_logs', 'bgp_peer_status')
    op.drop_column('telemetry_logs', 'vpn_tunnels_up')
    op.drop_column('telemetry_logs', 'bw_out')
    op.drop_column('telemetry_logs', 'bw_in')
    op.drop_column('incidents', 'resolved_by')
    op.drop_column('incidents', 'assigned_to')
    op.drop_column('incidents', 'updated_at')
    op.drop_index(op.f('ix_incident_timelines_incident_id'), table_name='incident_timelines')
    op.drop_index(op.f('ix_incident_timelines_id'), table_name='incident_timelines')
    op.drop_index(op.f('ix_incident_timelines_changed_at'), table_name='incident_timelines')
    op.drop_table('incident_timelines')
    op.drop_index(op.f('ix_compliance_reports_incident_id'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_id'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_generated_at'), table_name='compliance_reports')
    op.drop_table('compliance_reports')
    op.drop_index(op.f('ix_slack_messages_user_id'), table_name='slack_messages')
    op.drop_index(op.f('ix_slack_messages_timestamp'), table_name='slack_messages')
    op.drop_index(op.f('ix_slack_messages_id'), table_name='slack_messages')
    op.drop_index(op.f('ix_slack_messages_channel_id'), table_name='slack_messages')
    op.drop_table('slack_messages')
    op.drop_index(op.f('ix_background_tasks_task_id'), table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_status'), table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_id'), table_name='background_tasks')
    op.drop_table('background_tasks')
    op.drop_index(op.f('ix_automation_jobs_status'), table_name='automation_jobs')
    op.drop_index(op.f('ix_automation_jobs_job_id'), table_name='automation_jobs')
    op.drop_index(op.f('ix_automation_jobs_id'), table_name='automation_jobs')
    op.drop_index(op.f('ix_automation_jobs_device_name'), table_name='automation_jobs')
    op.drop_table('automation_jobs')
    # ### end Alembic commands ###
